---
- name: nfs server setup
  hosts: localhost
  gather_facts: false
  tasks:
    - name: install nfs-krenel-server
      ansible.builtin.package:
        name: nfs-kernel-server
        state: present
        update_cache: true
        install_recommends: true
      become: true
    
    - name: start nfs-server
      ansible.builtin.service:
        name: nfs-server
        state: started
        enabled: true
      become: true

    - name: configure NFS server
      ansible.builtin.lineinfile:
        path: /etc/exports
        regexp: '^/export/k8s'
        line: '/export/k8s *(rw,sync,no_root_squash,no_subtree_check)'
      notify: restart nfs-server

    - name: create export directory
      ansible.builtin.file:
        path: /export/k8s
        state: directory
        owner: root
        group: root
        mode: '0700'
        recurse: true
      become: true

  handlers:
    - name: restart nfs-server
      ansible.builtin.service:
        name: nfs-server
        state: restarted
        enabled: true
      become: true